export const THEME_PRESETS = [
  {
    id: 'default',
    name: 'Sistema Padrão',
    description: 'Tema padrão do sistema (use este para resetar)',
    palette: {
      background: '0 0% 100%',
      foreground: '240 10% 3.9%',
      primary: '221.2 83.2% 53.3%',
      primaryForeground: '210 40% 98%',
      secondary: '210 40% 96.1%',
      secondaryForeground: '222.2 47.4% 11.2%',
      accent: '210 40% 96.1%',
      accentForeground: '222.2 47.4% 11.2%',
      card: '0 0% 100%',
      cardForeground: '240 10% 3.9%',
      muted: '210 40% 96.1%',
      mutedForeground: '215.4 16.3% 46.9%',
    },
    layout: {
      cardStyle: 'default' as const,
      borderRadius: '0.5rem',
      shadowIntensity: 'medium' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'ease-in-out',
      transitions: ['all'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'ocean',
    name: 'Oceano',
    description: 'Tons de azul e verde água',
    palette: {
      background: '210 40% 98%',
      foreground: '215 25% 27%',
      primary: '199 89% 48%',
      primaryForeground: '0 0% 100%',
      secondary: '187 85% 43%',
      secondaryForeground: '0 0% 100%',
      accent: '142 76% 36%',
      accentForeground: '0 0% 100%',
      card: '0 0% 100%',
      cardForeground: '215 25% 27%',
      muted: '210 40% 96.1%',
      mutedForeground: '215.4 16.3% 46.9%',
    },
    layout: {
      cardStyle: 'elevated' as const,
      borderRadius: '0.75rem',
      shadowIntensity: 'medium' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitions: ['all'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'sunset',
    name: 'Pôr do Sol',
    description: 'Tons quentes de laranja e rosa',
    palette: {
      background: '30 40% 99%',
      foreground: '20 14.3% 4.1%',
      primary: '24 95% 53%',
      primaryForeground: '0 0% 100%',
      secondary: '350 89% 60%',
      secondaryForeground: '0 0% 100%',
      accent: '346 77% 50%',
      accentForeground: '0 0% 100%',
      card: '0 0% 100%',
      cardForeground: '20 14.3% 4.1%',
      muted: '30 40% 96%',
      mutedForeground: '25 16% 47%',
    },
    layout: {
      cardStyle: 'bordered' as const,
      borderRadius: '0.5rem',
      shadowIntensity: 'light' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'fast',
      easing: 'ease-out',
      transitions: ['colors', 'opacity'],
      hover: true,
      focus: true,
      pageTransitions: false,
    },
  },
  {
    id: 'forest',
    name: 'Floresta',
    description: 'Verde natural e terroso',
    palette: {
      background: '120 20% 98%',
      foreground: '120 10% 15%',
      primary: '142 71% 45%',
      primaryForeground: '0 0% 100%',
      secondary: '85 60% 45%',
      secondaryForeground: '0 0% 100%',
      accent: '64 82% 51%',
      accentForeground: '120 10% 15%',
      card: '0 0% 100%',
      cardForeground: '120 10% 15%',
      muted: '120 20% 96%',
      mutedForeground: '120 10% 45%',
    },
    layout: {
      cardStyle: 'default' as const,
      borderRadius: '0.5rem',
      shadowIntensity: 'medium' as const,
      spacing: 'spacious' as const,
    },
    animations: {
      enabled: true,
      duration: 'slow',
      easing: 'ease-in-out',
      transitions: ['all'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'midnight',
    name: 'Meia-Noite',
    description: 'Roxo profundo e elegante',
    palette: {
      background: '270 20% 98%',
      foreground: '270 15% 10%',
      primary: '262 83% 58%',
      primaryForeground: '0 0% 100%',
      secondary: '270 50% 40%',
      secondaryForeground: '0 0% 100%',
      accent: '290 70% 50%',
      accentForeground: '0 0% 100%',
      card: '0 0% 100%',
      cardForeground: '270 15% 10%',
      muted: '270 20% 96%',
      mutedForeground: '270 10% 45%',
    },
    layout: {
      cardStyle: 'elevated' as const,
      borderRadius: '1rem',
      shadowIntensity: 'strong' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      transitions: ['transforms', 'opacity'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'minimal',
    name: 'Minimalista',
    description: 'Design limpo e monocromático',
    palette: {
      background: '0 0% 100%',
      foreground: '0 0% 10%',
      primary: '0 0% 20%',
      primaryForeground: '0 0% 98%',
      secondary: '0 0% 90%',
      secondaryForeground: '0 0% 10%',
      accent: '0 0% 85%',
      accentForeground: '0 0% 10%',
      card: '0 0% 100%',
      cardForeground: '0 0% 10%',
      muted: '0 0% 96%',
      mutedForeground: '0 0% 45%',
    },
    layout: {
      cardStyle: 'flat' as const,
      borderRadius: '0.25rem',
      shadowIntensity: 'none' as const,
      spacing: 'compact' as const,
    },
    animations: {
      enabled: false,
      duration: 'fast',
      easing: 'ease-in-out',
      transitions: [],
      hover: false,
      focus: false,
      pageTransitions: false,
    },
  },
  {
    id: 'dark-slate',
    name: 'Slate Escuro',
    description: 'Tema escuro elegante com tons de cinza',
    palette: {
      background: '222.2 84% 4.9%',
      foreground: '210 40% 98%',
      primary: '217.2 91.2% 59.8%',
      primaryForeground: '222.2 47.4% 11.2%',
      secondary: '217.2 32.6% 17.5%',
      secondaryForeground: '210 40% 98%',
      accent: '217.2 32.6% 17.5%',
      accentForeground: '210 40% 98%',
      card: '222.2 84% 4.9%',
      cardForeground: '210 40% 98%',
      muted: '217.2 32.6% 17.5%',
      mutedForeground: '215 20.2% 65.1%',
    },
    layout: {
      cardStyle: 'bordered' as const,
      borderRadius: '0.5rem',
      shadowIntensity: 'strong' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'ease-in-out',
      transitions: ['all'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'dark-purple',
    name: 'Roxo Noturno',
    description: 'Tema escuro com toques de roxo vibrante',
    palette: {
      background: '240 10% 3.9%',
      foreground: '0 0% 98%',
      primary: '263.4 70% 50.4%',
      primaryForeground: '0 0% 100%',
      secondary: '240 4.8% 15.9%',
      secondaryForeground: '0 0% 98%',
      accent: '240 4.8% 15.9%',
      accentForeground: '0 0% 98%',
      card: '240 10% 3.9%',
      cardForeground: '0 0% 98%',
      muted: '240 3.7% 15.9%',
      mutedForeground: '240 5% 64.9%',
    },
    layout: {
      cardStyle: 'elevated' as const,
      borderRadius: '0.75rem',
      shadowIntensity: 'medium' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitions: ['all'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
  {
    id: 'dark-emerald',
    name: 'Esmeralda Escuro',
    description: 'Tema escuro com acentos verdes',
    palette: {
      background: '20 14.3% 4.1%',
      foreground: '0 0% 95%',
      primary: '142.1 76.2% 36.3%',
      primaryForeground: '355.7 100% 97.3%',
      secondary: '240 3.7% 15.9%',
      secondaryForeground: '0 0% 98%',
      accent: '12 6.5% 15.1%',
      accentForeground: '0 0% 98%',
      card: '24 9.8% 10%',
      cardForeground: '0 0% 95%',
      muted: '0 0% 15%',
      mutedForeground: '240 5% 64.9%',
    },
    layout: {
      cardStyle: 'default' as const,
      borderRadius: '0.5rem',
      shadowIntensity: 'light' as const,
      spacing: 'comfortable' as const,
    },
    animations: {
      enabled: true,
      duration: 'normal',
      easing: 'ease-in-out',
      transitions: ['colors', 'opacity'],
      hover: true,
      focus: true,
      pageTransitions: true,
    },
  },
];

export type ThemePreset = (typeof THEME_PRESETS)[0];
